resources:
  - name: x86_64_CentOS_7_prep_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/x86_64.CentOS_7.prep
      branch: master

  - name: CentOS7_bits_access_cli
    type: cliConfig
    integration: aws_bits_access
    pointer:
      region: us-east-1
      
  - name: c7_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/c7
      branch: master

  - name: c7_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/c7"
    seed:
      versionName: master

  - name: c7all_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: dry-dock/c7all
      branch: master

  - name: c7all_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/c7all"
    seed:
      versionName: master

  - name: c7_dh_cli
    type: cliConfig
    integration: shipDH

  - name: CentOS7_reqExec_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/reqExec
      branch: master

jobs:
  - name: reqExec_x86_64_CentOS_7_pack
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_c07_cus_01
    steps:
      - IN: x86_64_CentOS_7_prep_repo
        switch: off
      - IN: CentOS7_bits_access_cli
        switch: off
      - IN: CentOS7_reqExec_repo
      - TASK:
          name: create_centOS7_artifacts
          script:
            - pushd $(shipctl get_resource_state "x86_64_CentOS_7_prep_repo")
            - ./buildAndPushReqExecArtifacts.sh CentOS7_reqExec_repo
            - popd
            
  - name: x86_64_CentOS_7_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_CentOS_7_prep_repo
        switch: off
      - IN: c7_dh_cli
        switch: off
      - IN: c7_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_CentOS_7_prep_repo")
            - ./buildImage.sh c7 x86_64_CentOS_7_prep
            - popd
      - OUT: c7_img

  - name: all_x86_64_CentOS_7_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: x86_64_CentOS_7_prep_repo
        switch: off
      - IN: c7_dh_cli
        switch: off
      - IN: c7_img
      - IN: c7all_repo
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "x86_64_CentOS_7_prep_repo")
            - ./buildImage.sh c7all all_x86_64_CentOS_7_prep
            - docker run "drydock/c7all:master" "/c7all/services/service_test.sh"
            - popd
      - OUT: c7all_img
